### ISSUE TITLE
list index out of range: Pootle error when assigning permissions to some users in translationprojects

### ISSUE THREAD

**Issue by capiscuas** [capiscuas/pootle#10]
When trying to add an user Pandalaft
http://pootle.linguisticteam.org/es/designing_the_future/admin_permissions.html

pootle fails and outputs the following error in the apache.log

[Sat Feb 02 13:25:11 2013] [error] Traceback (most recent call last):
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
[Sat Feb 02 13:25:11 2013] [error]     response = callback(request, _callback_args, *_callback_kwargs)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/language/view.py", line 59, in decorated_f
[Sat Feb 02 13:25:11 2013] [error]     return f(request, translation_project, _args, *_kwargs)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/language/view.py", line 75, in decorated_f
[Sat Feb 02 13:25:11 2013] [error]     return f(request, translation_project, _args, *_kwargs)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/admin/util.py", line 56, in decorated_f
[Sat Feb 02 13:25:11 2013] [error]     return f(request, path_obj, _args, *_kwargs)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_translationproject/views.py", line 82, in admin_permissions
[Sat Feb 02 13:25:11 2013] [error]     template_vars)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/admin/permissions.py", line 112, in admin_permissions
[Sat Feb 02 13:25:11 2013] [error]     can_delete=True, form=PermissionSetForm)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/admin/util.py", line 223, in edit
[Sat Feb 02 13:25:11 2013] [error]     queryset=queryset, **kwargs)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/admin/util.py", line 201, in process_modelformset
[Sat Feb 02 13:25:11 2013] [error]     formset = formset_class(request.POST, queryset=objects.object_list)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/forms/models.py", line 424, in **init**
[Sat Feb 02 13:25:11 2013] [error]     super(BaseModelFormSet, self).**init**(**defaults)
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/forms/formsets.py", line 50, in **init**
[Sat Feb 02 13:25:11 2013] [error]     self._construct_forms()
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/forms/formsets.py", line 115, in _construct_forms
[Sat Feb 02 13:25:11 2013] [error]     self.forms.append(self._construct_form(i))
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/forms/models.py", line 451, in _construct_form
[Sat Feb 02 13:25:11 2013] [error]     kwargs['instance'] = self.get_queryset()[i]
[Sat Feb 02 13:25:11 2013] [error]   File "/var/www/vhosts/pootle.linguisticteam.org/env/lib/python2.6/site-packages/django/db/models/query.py", line 190, in __getitem__
[Sat Feb 02 13:25:11 2013] [error]     return self._result_cache[k]
[Sat Feb 02 13:25:11 2013] [error] IndexError: list index out of range
[Sat Feb 02 13:25:11 2013] [error]

**Comment by capiscuas** [comment]
I added the following debug code in /var/www/vhosts/pootle.linguisticteam.org/src/pootle/apps/pootle_app/views/admin/util.py:

```
if request.method == 'POST' and request.POST:
    # Create a formset from all the 'model_class' instances whose values
    # will be updated using the contents of request.POST
    objects = paginate(request, queryset)
    print 'OBJECT_LIST'
    print request.POST
    print objects.object_list
    formset = formset_class(request.POST, queryset=objects.object_list)
```

and I'm getting the following before the error happens
[Sat Feb 02 13:58:30 2013] [error] OBJECT_LIST
[Sat Feb 02 13:58:30 2013] [error] <QueryDict: {u'form-40-directory': [u'478'], u'form-22-directory': [u'478'], u'form-16-profile': [u'294'], u'form-4-id': [u'339'], u'form-30-id': [u'3142'], u'form-33-positive_permissions': [u'35', u'34'], u'form-4-profile': [u'89'], u'form-36-id': [u'3673'], u'form-55-id': [u'6007'], u'form-56-id': [u'6191'], u'form-40-positive_permissions': [u'35', u'34'], u'form-3-id': [u'333'], u'form-55-positive_permissions': [u'35', u'34'], u'form-13-positive_permissions': [u'35', u'34'], u'form-1-directory': [u'478'], u'form-47-id': [u'5126'], u'form-2-directory': [u'478'], u'form-36-positive_permissions': [u'35', u'34'], u'form-31-profile': [u'875'], u'form-16-directory': [u'478'], u'form-26-id': [u'2704'], u'form-51-directory': [u'478'], u'form-46-positive_permissions': [u'34'], u'form-58-positive_permissions': [u'35', u'34'], u'form-52-directory': [u'478'], u'form-27-id': [u'2785'], u'form-23-positive_permissions': [u'35', u'34'], u'form-17-positive_permissions': [u'34'], u'form-6-id': [u'344'], u'form-11-directory': [u'478'], u'form-5-id': [u'336'], u'form-34-id': [u'4566'], u'form-17-id': [u'2301'], u'form-58-id': [u'6601'], u'form-33-id': [u'3270'], u'form-19-directory': [u'478'], u'form-50-positive_permissions': [u'35', u'34'], u'form-43-id': [u'4528'], u'form-8-directory': [u'478'], u'form-41-id': [u'4416'], u'form-23-id': [u'1959'], u'form-47-positive_permissions': [u'35', u'34'], u'form-44-positive_permissions': [u'35', u'34'], u'form-53-positive_permissions': [u'35', u'34'], u'form-38-profile': [u'1039'], u'form-11-id': [u'334'], u'form-6-directory': [u'478'], u'form-58-profile': [u'1520'], u'form-18-id': [u'1473'], u'form-28-id': [u'3118'], u'form-59-directory': [u'478'], u'form-26-profile': [u'690'], u'form-16-id': [u'1237'], u'form-12-positive_permissions': [u'35', u'34'], u'form-49-positive_permissions': [u'35', u'34'], u'form-24-directory': [u'478'], u'form-22-id': [u'1861'], u'form-47-profile': [u'1242'], u'form-39-directory': [u'478'], u'form-24-id': [u'1990'], u'form-44-directory': [u'478'], u'form-15-profile': [u'291'], u'form-55-profile': [u'1420'], u'form-50-profile': [u'1264'], u'form-30-profile': [u'864'], u'form-32-profile': [u'889'], u'form-22-positive_permissions': [u'35', u'34'], u'form-54-directory': [u'478'], u'form-0-id': [u'3221'], u'form-15-positive_permissions': [u'35', u'34'], u'form-50-id': [u'5237'], u'form-29-id': [u'3143'], u'form-52-positive_permissions': [u'35', u'34'], u'form-7-profile': [u'117'], u'form-51-positive_permissions': [u'35', u'34'], u'form-23-profile': [u'460'], u'form-37-positive_permissions': [u'35', u'34'], u'form-35-directory': [u'478'], u'form-26-positive_permissions': [u'35', u'34'], u'form-54-positive_permissions': [u'35', u'34'], u'form-14-directory': [u'478'], u'form-12-profile': [u'197'], u'form-19-profile': [u'370'], u'form-21-id': [u'1862'], u'form-27-positive_permissions': [u'35', u'34'], u'form-7-positive_permissions': [u'35', u'34'], u'form-30-directory': [u'478'], u'form-2-id': [u'335'], u'form-1-profile': [u'27'], u'form-1-id': [u'6546'], u'form-5-profile': [u'90'], u'form-8-profile': [u'142'], u'form-54-profile': [u'1376'], u'form-29-profile': [u'863'], u'form-37-directory': [u'478'], u'form-18-directory': [u'478'], u'form-3-positive_permissions': [u'35', u'34'], u'form-45-profile': [u'1223'], u'form-13-profile': [u'201'], u'form-49-profile': [u'1259'], u'form-9-profile': [u'146'], u'form-TOTAL_FORMS': [u'60'], u'form-32-id': [u'3208'], u'form-3-directory': [u'478'], u'form-5-directory': [u'478'], u'form-43-positive_permissions': [u'35', u'34'], u'form-25-id': [u'2051'], u'form-41-profile': [u'1142'], u'form-25-directory': [u'478'], u'form-4-directory': [u'478'], u'form-57-positive_permissions': [u'35', u'34'], u'form-59-id': [u''], u'form-39-positive_permissions': [u'35', u'34'], u'form-21-positive_permissions': [u'35', u'34'], u'form-20-profile': [u'387'], u'form-36-profile': [u'992'], u'form-8-positive_permissions': [u'35', u'34'], u'form-53-profile': [u'1365'], u'form-11-profile': [u'183'], u'form-0-positive_permissions': [u'35', u'34'], u'form-42-directory': [u'478'], u'form-57-id': [u'6296'], u'form-52-id': [u'5539'], u'form-10-directory': [u'478'], u'form-20-positive_permissions': [u'35', u'34'], u'form-24-profile': [u'470'], u'form-2-positive_permissions': [u'35', u'34'], u'form-35-id': [u'3584'], u'form-21-directory': [u'478'], u'form-22-profile': [u'429'], u'form-58-directory': [u'478'], u'form-33-profile': [u'910'], u'form-6-positive_permissions': [u'35', u'34'], u'form-48-id': [u'5145'], u'form-45-directory': [u'478'], u'form-47-directory': [u'478'], u'form-44-profile': [u'1178'], u'form-41-positive_permissions': [u'35', u'34'], u'form-29-positive_permissions': [u'35', u'34'], u'form-9-id': [u'343'], u'form-7-directory': [u'478'], u'form-4-positive_permissions': [u'35', u'34'], u'form-11-positive_permissions': [u'35', u'34'], u'form-12-directory': [u'478'], u'form-32-directory': [u'478'], u'form-34-profile': [u'956'], u'form-20-directory': [u'478'], u'form-51-id': [u'5507'], u'form-49-id': [u'5208'], u'form-32-positive_permissions': [u'35', u'34'], u'form-28-profile': [u'852'], u'form-57-directory': [u'478'], u'form-27-profile': [u'743'], u'form-12-id': [u'338'], u'form-48-directory': [u'478'], u'form-13-directory': [u'478'], u'form-57-profile': [u'1457'], u'form-53-directory': [u'478'], u'form-6-profile': [u'93'], u'form-5-positive_permissions': [u'35', u'34'], u'form-35-profile': [u'972'], u'form-43-directory': [u'478'], u'form-14-id': [u'782'], u'form-INITIAL_FORMS': [u'59'], u'form-2-profile': [u'82'], u'form-42-positive_permissions': [u'35', u'34'], u'form-52-profile': [u'1324'], u'form-56-profile': [u'1445'], u'form-28-positive_permissions': [u'35', u'34'], u'form-29-directory': [u'478'], u'form-30-positive_permissions': [u'35', u'34'], u'form-MAX_NUM_FORMS': [u''], u'form-46-profile': [u'1233'], u'form-14-profile': [u'248'], u'form-54-id': [u'5754'], u'form-56-directory': [u'478'], u'form-15-directory': [u'478'], u'form-46-id': [u'5270'], u'form-48-profile': [u'1243'], u'form-37-profile': [u'994'], u'form-0-directory': [u'478'], u'form-39-id': [u'3936'], u'form-17-directory': [u'478'], u'form-27-directory': [u'478'], u'form-38-id': [u'3872'], u'form-36-directory': [u'478'], u'form-19-positive_permissions': [u'35', u'34'], u'form-42-profile': [u'1147'], u'form-26-directory': [u'478'], u'form-13-id': [u'477'], u'form-28-directory': [u'478'], u'form-0-profile': [u'8'], u'form-10-id': [u'342'], u'form-59-profile': [u'1561'], u'form-50-directory': [u'478'], u'form-43-profile': [u'1163'], u'form-59-positive_permissions': [u'35', u'34'], u'form-37-id': [u'3700'], u'form-38-positive_permissions': [u'35', u'34'], u'form-8-id': [u'341'], u'form-18-positive_permissions': [u'35', u'34'], u'form-49-directory': [u'478'], u'form-35-positive_permissions': [u'35', u'34'], u'form-46-directory': [u'478'], u'form-23-directory': [u'478'], u'form-19-id': [u'3128'], u'form-17-profile': [u'344'], u'form-14-positive_permissions': [u'35', u'34'], u'form-9-directory': [u'478'], u'form-53-id': [u'5736'], u'form-40-id': [u'4140'], u'form-42-id': [u'4409'], u'form-38-directory': [u'478'], u'csrfmiddlewaretoken': [u'GIfBbkeFTujOs7U5kAtANPF2n8UxqGX5'], u'form-45-positive_permissions': [u'35', u'34'], u'form-31-positive_permissions': [u'35', u'34'], u'form-51-profile': [u'1317'], u'form-18-profile': [u'352'], u'form-25-profile': [u'494'], u'form-31-id': [u'3160'], u'form-45-id': [u'4957'], u'form-31-directory': [u'478'], u'form-41-directory': [u'478'], u'form-10-positive_permissions': [u'35', u'34'], u'form-24-positive_permissions': [u'35', u'34'], u'form-34-directory': [u'478'], u'form-7-id': [u'337'], u'form-15-id': [u'1236'], u'form-16-positive_permissions': [u'35', u'34'], u'form-40-profile': [u'1092'], u'form-44-id': [u'4727'], u'form-55-directory': [u'478'], u'form-10-profile': [u'149'], u'form-33-directory': [u'478'], u'form-20-id': [u'1795'], u'form-39-profile': [u'1054'], u'form-9-positive_permissions': [u'35', u'34'], u'form-34-positive_permissions': [u'35', u'34'], u'form-3-profile': [u'85'], u'form-25-positive_permissions': [u'35', u'34'], 

[Sat Feb 02 13:58:30 2013] [error] [<PermissionSet: DannySpain : /es/designing_the_future/>, <PermissionSet: unionearth : /es/designing_the_future/>, <PermissionSet: Danny2010es : /es/designing_the_future/>, <PermissionSet: aganon77 : /es/designing_the_future/>, <PermissionSet: ilam : /es/designing_the_future/>, <PermissionSet: gekko066 : /es/designing_the_future/>, <PermissionSet: Yayita : /es/designing_the_future/>, <PermissionSet: gr4m : /es/designing_the_future/>, <PermissionSet: matu : /es/designing_the_future/>, <PermissionSet: yagonuchera : /es/designing_the_future/>, <PermissionSet: oscar.olivera : /es/designing_the_future/>, <PermissionSet: ArnauVK : /es/designing_the_future/>, <PermissionSet: historix49 : /es/designing_the_future/>, <PermissionSet: duqueperin : /es/designing_the_future/>, <PermissionSet: Icavot : /es/designing_the_future/>, <PermissionSet: Brouagh : /es/designing_the_future/>, <PermissionSet: josemanuelsalgado : /es/designing_the_future/>, <PermissionSet: Fer Ghingaro : /es/designing_the_future/>, <PermissionSet: nidrashanti : /es/designing_the_future/>, <PermissionSet: txetxo : /es/designing_the_future/>, '...(remaining elements truncated)...']

..

**Comment by capiscuas** [comment]
Apparently the improvement
https://github.com/capiscuas/pootle/issues/6

made this bug to happen.
I reverted back the pagination.
