### ISSUE TITLE
Unable to run Pootle commands in shell

### ISSUE THREAD

**Issue by LTIOfficial** [capiscuas/pootle#31]
Running any pootle commands in shell produces an error similar to the one below.

$ python manage.py sync_stores
2014-03-06 08:39:29,305 INFO Change ID is zero, ignoring altogether.
2014-03-06 08:39:30,196 ERROR Failed to run sync_stores over /ro/activist_orientation_guide/'s files
'NoneType' object has no attribute 'user'
2014-03-06 08:39:40,040 ERROR Failed to run sync_stores over /zh_TW/venus_project_site/'s files
'NoneType' object has no attribute 'user'

Trying python26 in place of python yields a different error

$ python26 manage.py sync_stores
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    from pootle import settings, syspath_override
  File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/settings.py", line 22, in <module>
    execfile(os.path.abspath(f))
  File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/settings/95-outro.conf", line 36, in <module>
    from pootle.i18n import override, gettext_live, gettext
  File "/var/www/vhosts/pootle.linguisticteam.org/src/pootle/i18n/override.py", line 32, in <module>
    from translate.lang import data
ImportError: No module named translate.lang

**Comment by LTIOfficial** [comment]
Current results for same python2.6 command:

python2.6 manage.py sync_stores
2014-05-09 20:32:56,871 INFO Change ID is zero, ignoring altogether.
2014-05-09 20:32:57,417 ERROR Failed to run sync_stores over /ro/activist_orientation_guide/'s files
'NoneType' object has no attribute 'user'
2014-05-09 20:33:05,165 ERROR Failed to run sync_stores over /zh_TW/venus_project_site/'s files
'NoneType' object has no attribute 'user'
